//Package services generated by service-enroll-generate.go;
// !DO NOT EDIT THIS FILE!
package service

import (
	
	"backend/serve/article" //article ,  article, , 389403710@qq.com
	"backend/serve/chat" //chat ,  chat, , 389403710@qq.com
	"backend/serve/filemanage" //filemanage ,  filemanage, , 389403710@qq.com
	"backend/serve/jwt" //jwt ,  jwt-Login, , 389403710@qq.com
	"backend/serve/login" //login ,  login, , 389403710@qq.com
	"backend/serve/msgmanage" //msgmanage ,  msgmanage, , 389403710@qq.com
	"backend/serve/test" //test ,  test, , XUnion@GMail.com
	"backend/serve/userlist" //userlist ,  userlist, , XUnion@GMail.com
)

//Enroll will be called from serve cmd
func Enroll(){
  
  article.Enroll(`{"name":"article","email":"389403710@qq.com"}`)
  chat.Enroll(`{"name":"chat","email":"389403710@qq.com"}`)
  filemanage.Enroll(`{"name":"filemanage","email":"389403710@qq.com"}`)
  jwt.Enroll(`{"name":"jwt-Login","email":"389403710@qq.com"}`)
  login.Enroll(`{"name":"login","email":"389403710@qq.com"}`)
  msgmanage.Enroll(`{"name":"msgmanage","email":"389403710@qq.com"}`)
  test.Enroll(`{"name":"test","email":"XUnion@GMail.com"}`)
  userlist.Enroll(`{"name":"userlist","email":"XUnion@GMail.com"}`)
}
